name:issuecommand
on:
  issues:
    types:[opened]

jobs:
  comment_with_action:
     runs_on:ubuntu_latest
     steps:
       -name:"dump github context"
        run:echo '${{ toJSON(github.event)  }}' | jq
        shell:bash
